"""
Message Entity.

Represents a single message in a conversation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

from tacto.domain.messaging.value_objects.message_direction import MessageDirection
from tacto.domain.messaging.value_objects.message_source import MessageSource
from tacto.domain.shared.value_objects import ConversationId, MessageId


@dataclass
class Message:
    """
    Message Entity.

    Represents a single message within a conversation.
    Messages are immutable once created - they represent historical records.

    Invariants:
    - Body cannot be empty
    - Must have valid direction and source
    - Timestamp must be set
    """

    id: MessageId
    conversation_id: ConversationId
    body: str
    direction: MessageDirection
    source: MessageSource
    from_me: bool
    timestamp: datetime
    external_id: Optional[str] = None
    media_url: Optional[str] = None
    media_type: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self) -> None:
        """Validate invariants."""
        if not self.body or not self.body.strip():
            from tacto.domain.shared.exceptions import ValidationError
            raise ValidationError(
                message="Message body cannot be empty",
                field="body",
            )

    @property
    def is_incoming(self) -> bool:
        """Check if message is from customer."""
        return self.direction == MessageDirection.INCOMING

    @property
    def is_outgoing(self) -> bool:
        """Check if message is to customer."""
        return self.direction == MessageDirection.OUTGOING

    @property
    def is_from_ai(self) -> bool:
        """Check if message was generated by AI."""
        return self.source == MessageSource.AI

    @property
    def is_human_intervention(self) -> bool:
        """Check if message indicates human intervention."""
        return self.source == MessageSource.PHONE and self.from_me

    @property
    def word_count(self) -> int:
        """Get word count of message body."""
        return len(self.body.split())

    @property
    def char_count(self) -> int:
        """Get character count of message body."""
        return len(self.body)

    @classmethod
    def create_incoming(
        cls,
        conversation_id: ConversationId,
        body: str,
        source: MessageSource,
        timestamp: datetime,
        external_id: Optional[str] = None,
        message_id: Optional[MessageId] = None,
    ) -> "Message":
        """Factory method for incoming messages."""
        return cls(
            id=message_id or MessageId.generate(),
            conversation_id=conversation_id,
            body=body,
            direction=MessageDirection.INCOMING,
            source=source,
            from_me=False,
            timestamp=timestamp,
            external_id=external_id,
        )

    @classmethod
    def create_outgoing(
        cls,
        conversation_id: ConversationId,
        body: str,
        source: MessageSource,
        message_id: Optional[MessageId] = None,
    ) -> "Message":
        """Factory method for outgoing messages."""
        return cls(
            id=message_id or MessageId.generate(),
            conversation_id=conversation_id,
            body=body,
            direction=MessageDirection.OUTGOING,
            source=source,
            from_me=True,
            timestamp=datetime.utcnow(),
        )
