"""
MessageSource Value Object.

Represents the source/origin of a message.
"""

from enum import StrEnum


class MessageSource(StrEnum):
    """
    Source of the message.

    - APP: Message from WhatsApp app (customer)
    - WEB: Message from WhatsApp Web (human operator - triggers AI disable)
    - PHONE: Message from phone/human operator (triggers AI disable)
    - AI: Message generated by AI assistant
    - HUMAN_OPERATOR: Explicit human operator intervention (triggers AI disable)
    """

    APP = "app"
    WEB = "web"
    PHONE = "phone"
    AI = "ai"
    HUMAN_OPERATOR = "human_operator"

    @property
    def is_human_intervention(self) -> bool:
        """Check if this source indicates human intervention (operator sent message)."""
        return self in (MessageSource.PHONE, MessageSource.WEB, MessageSource.HUMAN_OPERATOR)

    @property
    def is_ai_generated(self) -> bool:
        """Check if message was generated by AI."""
        return self == MessageSource.AI

    @property
    def is_from_customer(self) -> bool:
        """Check if message is from customer."""
        return self == MessageSource.APP
