"""
MessageSource Value Object.

Represents the source/origin of a message.
"""

from enum import StrEnum


class MessageSource(StrEnum):
    """
    Source of the message.

    - APP: Message from WhatsApp app (customer)
    - PHONE: Message from phone/human operator (triggers AI disable)
    - AI: Message generated by AI assistant
    """

    APP = "app"
    PHONE = "phone"
    AI = "ai"

    @property
    def is_human_intervention(self) -> bool:
        """Check if this source indicates human intervention."""
        return self == MessageSource.PHONE

    @property
    def is_ai_generated(self) -> bool:
        """Check if message was generated by AI."""
        return self == MessageSource.AI

    @property
    def is_from_customer(self) -> bool:
        """Check if message is from customer."""
        return self == MessageSource.APP
